version: "2"

services:
  nginx:
    container_name: "ifarmer_nginx"
    build: ./docker/nginx
    links:
      - frontend:frontend
    volumes:
      - ./log/ifarmer/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ifarmer-web
      - ifarmer_ifarmer-vn
      - docker-elk_elk
#    command: "/bin/sh -c 'while :; do sleep 168h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:v0.36.0
    volumes:
      - ./log/ifarmer/letsencrypt:/var/log/letsencrypt
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 168h & wait $${!}; done;'"

  frontend:
    build: ./frontend
    container_name: "ifarmer_prod"
    volumes:
      - ./frontend:/var/www/ifarmer
      - ./frontend/node_modules:/var/www/ifarmer/node_modules
    ports:
      - "3000:3000"
    networks:
      - ifarmer-web
      - docker-elk_elk
      - cms_cms
      - ifarmer_ifarmer-vn
    command: "pm2 start --no-daemon server.js -i 1"

networks:
  ifarmer-web:
    driver: bridge
  docker-elk_elk:
    external: true
  cms_cms:
    external: true
  ifarmer_ifarmer-vn:
    external: true
