version: "2"

services:
  nginx:
    container_name: "ifarmer_nginx"
    build: ./docker/nginx
    links:
      - frontend:frontend
    volumes:
      - /var/log/ifarmer/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ifarmer-web
      - ifarmer_ifarmer-vn
      - docker-elk_elk

  frontend:
    build: ./frontend
    container_name: "ifarmer_prod"
    volumes:
      - ./frontend:/var/www/ifarmer
      - ./frontend/node_modules:/var/www/ifarmer/node_modules
    ports:
      - "3000:3000"
    networks:
      - ifarmer-web
      - docker-elk_elk
      - cms_cms
      - ifarmer_ifarmer-vn
    command: "pm2 start --no-daemon server.js -i 1"

networks:
  ifarmer-web:
    driver: bridge
  docker-elk_elk:
    external: true
  cms_cms:
    external: true
  ifarmer_ifarmer-vn:
    external: true
